import { env } from "cloudflare:workers";
import { notFound } from "next/navigation";
import { MessageCircle } from "lucide-react";
import { getCommunityUser } from "../../community-auth";
import { CommunityHeader } from "../community-header";
import { ReplyForm } from "../community-actions";
import { isOfficialCommunityUser, OFFICIAL_COMMUNITY_NAME } from "../../community-official";
export const dynamic="force-dynamic";
type Post={id:number;title:string;body:string;platform:string;kind:string;createdAt:string;username:string};type Comment={id:number;body:string;createdAt:string;username:string;userId:string};
export default async function Thread({params}:{params:Promise<{id:string}>}){const user=await getCommunityUser();const{id}=await params;let post:Post|null=null;let comments:Comment[]=[];try{if(env.DB){post=await env.DB.prepare(`SELECT p.id,p.title,p.body,p.platform,p.kind,p.created_at AS createdAt,u.username FROM community_posts p JOIN community_users u ON u.id=p.user_id WHERE p.id=? AND p.status='approved'`).bind(Number(id)).first<Post>();if(post){const result=await env.DB.prepare(`SELECT c.id,c.body,c.created_at AS createdAt,c.user_id AS userId,u.username FROM community_comments c JOIN community_users u ON u.id=c.user_id WHERE c.post_id=? AND c.status='approved' ORDER BY c.created_at`).bind(post.id).all<Comment>();comments=result.results}}}catch{}if(!post)notFound();return <main className="community-page"><CommunityHeader user={user}/><article className="community-thread"><div className="community-thread-meta"><b>{post.platform}</b><span>{post.kind}</span><span>@{post.username}</span><time>{new Date(post.createdAt).toLocaleDateString()}</time></div><h1>{post.title}</h1><div className="community-thread-body">{post.body.split(/\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</div><section className="replies"><h2><MessageCircle size={22}/> Replies</h2>{comments.length?comments.map(comment=>{const official=isOfficialCommunityUser(comment.userId);return <article className={official?"official-reply":undefined} key={comment.id}><div className="reply-author"><b>@{official?OFFICIAL_COMMUNITY_NAME:comment.username}</b>{official&&<span className="official-badge">OFFICIAL</span>}</div><time>{new Date(comment.createdAt).toLocaleDateString()}</time><p>{comment.body}</p></article>}):<p className="muted-copy">No approved replies yet.</p>}{user?<ReplyForm postId={post.id}/>:<p className="reply-login"><a href="/community/login">Sign in</a> to reply.</p>}</section></article></main>}
