"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Download, Search } from "lucide-react";
export type FeedPost = { id:number; title:string; excerpt:string; platform:string; kind:string; createdAt:string; featured:boolean|number; downloadName:string|null; imageName:string|null };
const filters=["All","PS6","PS5","PS4","PS3","Xbox","Switch","Retro","Breaking News"];
export function HomeFeed({initialPosts,initialQuery=""}:{initialPosts:FeedPost[];initialQuery?:string}){
 const [filter,setFilter]=useState("All"); const [query,setQuery]=useState(initialQuery);
 useEffect(()=>{const update=(event:Event)=>setQuery((event as CustomEvent<string>).detail||"");window.addEventListener("goldengames-search",update);return()=>window.removeEventListener("goldengames-search",update)},[]);
 const posts=useMemo(()=>initialPosts.filter(p=>{
   const matchesFilter=filter==="All"||(filter==="Breaking News"?p.kind===filter:p.platform.toLowerCase()===filter.toLowerCase());
   return matchesFilter&&(`${p.title} ${p.excerpt} ${p.kind}`).toLowerCase().includes(query.toLowerCase());
 }),[initialPosts,filter,query]);
 return <section className="content-section homepage-news-feed" id="latest"><div className="section-heading"><div><span className="eyebrow">THE NEXUS FEED</span><h2>Latest from the scene</h2></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search updates" aria-label="Search updates"/></label></div><div className="platform-tabs" id="platforms">{filters.map(i=><button key={i} className={filter===i?"active":""} onClick={()=>setFilter(i)}>{i}</button>)}</div><div className="news-grid">{posts.map((p,i)=><article key={p.id} className={i===0?"news-card featured-card":"news-card"}><div className={`card-visual visual-${p.platform.toLowerCase().replace(/\s/g,"-")}`}>{p.imageName&&<img src={`/api/images/${p.id}`} alt="" loading="lazy"/>}<span>{p.platform}</span><small>{p.kind}</small></div><div className="card-copy"><div className="meta"><b>{p.platform}</b><span>{p.kind}</span><time>{formatDate(p.createdAt)}</time></div><h3>{p.title}</h3><p>{p.excerpt}</p><div className="card-bottom">{p.downloadName?<a href={`/api/files/${p.id}`}><Download size={16}/> Download</a>:<span>Verified coverage</span>}<a href={`/news/${p.id}`} aria-label={`Read ${p.title}`}><ArrowUpRight size={19}/></a></div></div></article>)}{!posts.length&&<div className="empty-state"><Search size={28}/><h3>No updates found</h3><p>Try another platform, Breaking News, or a search term.</p></div>}</div><div className="download-strip" id="downloads"><div><span className="eyebrow">DOWNLOAD LIBRARY</span><h2>Files with context, not guesswork.</h2><p>Every downloadable item can include version, platform, author and compatibility notes.</p></div><a className="primary-btn" href="/downloads">Open library <ArrowUpRight size={18}/></a></div></section>;
}
function formatDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(d)}
